---
title: "Hw 7 resubmission"
output: md_document
date: "2024-03-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## HW: Two Events


1. Create a table of counts and proportions for the `cola` variable.  Report counts with proportions in parentheses, for example `23 (0.39)`.  (This is what is meant by  `N (p)`.)

| Colas     |   Not Colas |
| --------- | ----------- |
|  20(0.3)    |    46(0.7)    |

2. Create a similar table for the sugar preference variable.

| Regular   |   No Sugar |
| --------- | ----------- |
|  40(0.61)  |  26(0.39)    |

3. Use the data to generate a contingency table of counts and proportions.

|                   | Colas     |   Not Colas |
| ----------------- | --------- | ----------- |
| **Regular**       |  10(0.15)    |    30(0.45)    |
| **No sugar/Diet** | 10(0.15)     |    16(0.24)    |

4. Add to the table conditional column and row proportions and counts. With sugar preferences on the rows, the conditional row proportions are $P(\text{Drink}|\text{Sugar})$.  Likewise, with drink preferences on the columns, conditional column proportions are $P(\text{Sugar}|\text{Drink})$.

5. Add marginal proportions and counts.  The final table will look something like this:

|                            | Colas       |   Not Colas  | Total |
| -------------------------- | ----------- | ------------ | ------|
| **Regular**                |  10 (0.15)     |    30 (0.45)     | 40 (0.60) |
| &nbsp;&nbsp;&nbsp; Row     |  10 (0.25)     |    30 (0.75)     |       |
| &nbsp;&nbsp;&nbsp; Col     |  10 (0.5)      |    30 (0.6521)   |       |
| **No sugar/Diet**          |  10 (0.15)     |    16 (0.24)     | 26 (0.39) |
| &nbsp;&nbsp;&nbsp; Row     |  10 (0.3846)   |    16 (0.6154)   |       |
| &nbsp;&nbsp;&nbsp; Col     |  10 (0.5)      |    16 (0.3478)   |       |
| Total                      |  20 (0.30)     |    46 (0.69)     | 66 (1) |



